# global config
global:
  scrape_interval:     1m # Default is every 1 minute.
  evaluation_interval: 1m # Default is every 1 minute.
  scrape_timeout:      30s # Default is 10s.

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
# - "first_rules.yml"
# - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    # metrics_path defaults to '/metrics'
    scrape_interval: 2m
    static_configs:
      - targets: ['127.0.0.1:9090']

  - job_name: 'receive-actuator-prometheus'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['receive:8080']

  - job_name: 'materialize-actuator-prometheus'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['materialize:8080']
      
  - job_name: 'schedule-actuator-prometheus'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['schedule:8080']
      
  - job_name: 'jobadmin-actuator-prometheus'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['jobadmin:8080']